apiVersion: v1
kind: Service
metadata:
  name: noaa-exporter
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
spec:
  selector:
    app: noaa-exporter
  ports:
    - port: 8000
      targetPort: 8000
